### ISSUE TITLE
Add protocol 6 support for the Motorola Beepwear Pro

### ISSUE THREAD

**Issue by synthead** [wjhrdy/timex-datalink-caldav#1]
The latest version of timex_datalink_client, v0.12.1, now supports protocol 6 for the Motorola Beepwear Pro! This addition makes the library support all Datalink devices manufactured!

Protocol 6 only supports time, alarms, phone numbers, and various watch options, while timex-datalink-caldav exclusively writes appointments and anniversaries. So the only changes that would need to be implemented would be to recognize protocol 6 as valid, then basically do nothing with it.

Great job with this repo, by the way!

**Comment by wjhrdy** [comment]
cool, didn't even know about that watch! I'll add

**Comment by wjhrdy** [comment]
added protocol 6 and 9 with [894a87f](https://github.com/wjhrdy/timex-datalink-caldav/commit/894a87f02f6417a28aafbde7752aee43678a93b5)
