### ISSUE TITLE
timex-datalink-arudino now supports the Raspberry Pi Pico

### ISSUE THREAD

**Issue by synthead** [wjhrdy/timex-datalink-caldav#2]
Thought I'd mention that timex-datalink-arduino now has support for the Raspberry Pi Pico!

- https://github.com/synthead/timex-datalink-arduino

This is the PR that made this possible:

- https://github.com/synthead/timex-datalink-arduino/pull/17

**Comment by wjhrdy** [comment]
Oh amazing! I'll add to the readme

**Comment by wjhrdy** [comment]
added to the readme with 894a87f02f6417a28aafbde7752aee43678a93b5
